//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A1fxCrm.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerTicket = new HashSet<CustomerTicket>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string City { get; set; }
        public string Source { get; set; }
        public string Referance { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public int CustomerStatusId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CustomeCode { get; set; }
        public int ReRegisterCount { get; set; }
        public Nullable<System.DateTime> ReRegisterLastDateTime { get; set; }
        public bool ReRegisterChecked { get; set; }
    
        public virtual CustomerStatus CustomerStatus { get; set; }
        public virtual ICollection<CustomerTicket> CustomerTicket { get; set; }
        public virtual User User { get; set; }
    }
}
