//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionItem
    {
        public PermissionItem()
        {
            this.Role = new HashSet<Role>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string AreaName { get; set; }
        public string Group { get; set; }
        public Nullable<bool> RequiredAdministrator { get; set; }
    
        public virtual ICollection<Role> Role { get; set; }
    }
}
