//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.PermissionItem = new HashSet<PermissionItem>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string RoleName { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<PermissionItem> PermissionItem { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
